//! # attpc_merger
//!
//! attpc_merger is a Rust event builder and data merger inspired by [graw-merger](https://github.com/ATTPC/graw-merger) used to combine and convert `.graw` files generated by the AT-TPC data acquisition to the more universal and flexible [HDF5](https://www.hdfgroup.org/) format.
//!
//! ## Installation
//!
//! ### Rust
//!
//! If you have not used Rust before, you will most likely need to install the Rust tool chain. See the [Rust docs](https://www.rust-lang.org/tools/install) for installation instructions.
//!
//! ### Platform Support
//!
//! attpc_merger aims to support Linux, MacOS, and Windows. Currently, attpc_merger has been tested and built successfully on Ubuntu 22.04 and MacOS 13 (Ventura).
//!
//! ### Downloading
//!
//! To download attpc_merger clone the git repository using `git clone https://github.com/attpc/attpc_merger.git`
//!
//! ### HDF5
//!
//! Before building and running attpc_merger, HDF5 must be installed. Typically this will be installed using a package manager (homebrew, apt, etc), and the Rust libraries will auto detect the location of the HDF install. However, this is not always possible. Sometimes a newer version will need to be installed to a custom location. If this is the case, write the following snippet into the file `.cargo/config.toml` in the attpc_merger repository:
//!
//! ```[toml]
//! [env]
//! HDF5_DIR="/path/to/my/hdf5/install/"
//!
//! [build]
//! rustflags="-C link-args=-Wl,-rpath,/path/to/my/hdf5/install/lib"
//! ```
//!
//! Replace `/path/to/my/hdf5/install/` with the path to your HDF5 installation. The extra build command assumes that the hdf5 files are not installed to the normal library search path of your operating sytsem. Note that you will need to create the `.cargo` directory and the `config.toml` file.
//!
//! ### Building
//!
//! To build attpc_merger simply run `cargo build --release` from the attpc_merger repository to build the optimized release binary. To build debug version use `cargo build`. Note that if build errors are present and reference HDF5, your HDF5 install may be in a non-standard location. See the above section to specify custom HDF5 install locations to the build system.
//!
//! ### Running
//!
//! To run attpc_merger use `cargo run --release` from the attpc_merger repository. This will spawn the attpc_merger UI. Additionally, attpc_merger will log information to the terminal.
//!
//! ## Configuration
//!
//! The attpc_merger UI has 5 input fields that the user needs to fill out to process a run:
//!
//! - GRAW directory: Specifies the full-path to a directory which contains the AT-TPC graw structure (i.e. contains subdirectories of the run_# format)
//! - EVT directory: Specifies the full-path to a directory which contains the FRIBDAQ evt structure (i.e. contains subdirectories of the run# format)
//! - HDF5 directory: Specifies the full-path to a directory to which hdf5 (.h5) files will be written
//! - Pad map: Specifies the full path to a CSV file which contains the mapping information for AT-TPC pads and electronics
//! - Run Number: Which run should be processed
//!
//! The configuration can be saved (to a .yaml format) using File -> Save...
//! Configuration files can be loaded using File -> Open...
//! Using the Open buttons next to the directory/file fields will bring up a file dialog for those elements
//!
//! ### Online
//!
//! The attpc_merger UI additionally contains a button for toggling online mode. When toggled on, this changes the
//! interpretation of the various paths to match the behavior of the AT-TPC DAQ network. Only use this if you
//! know what you're doing.
//!
//! ## Output
//!
//! attpc_merger will output two files: the final resulting HDF5 data file, and a log file. Log files contain valuable information about the status of the application while building the merged data. If an error occurs, typically a warning will be printed to the terminal indicating that the user should check the log file. The log file will contain the detailed status of the run and indicate the issue that occurred. Log files are also useful because they can be easily shared when errors occur. It is not advised to delete the log files.
//!
//! ### HDF5 Data Format
//!
//! The data format used in the HDF5 data is as follows:
//!
//! - All FRIBDAQ data is within the Group "frib"
//! - FRIBDAQ Physics items are stored in the "evt" group
//! - FRIBDAQ Scaler items are stored in the "scaler" group
//! - All GET data is within the Group named "get"
//! - Each event has two Datasets. One is "evt#_data" and one is "evt#_header". The Datasets are named by event number (i.e. event 101 corresponds to Dataset evt101_data).
//! - The "header" Datasets contain metadata about the event (number and timestamp).
//! - Each "data" Dataset contains a two dimensional matrix of traces. Each row contains the data for a single trace from a pad in AT-TPC. The first five elements of the row contain the electronic address of the the pad (CoBo, AsAd, AGET, Channel, Pad in that order); the remaining 512 elements contain the trace data.
//! - Traces are stored in random order. That is, the Dataset matrix rows are not sorted by electronic address.
//!
//! Meta data can be found in many places. This will be cleaned up in future versions.

mod app;
use app::MergerApp;

/// The program entry point
#[allow(unreachable_code, dead_code)]
fn main() {
    simplelog::TermLogger::init(
        simplelog::LevelFilter::Info,
        simplelog::Config::default(),
        simplelog::TerminalMode::Mixed,
        simplelog::ColorChoice::Auto,
    )
    .unwrap();

    let mut native_options = eframe::NativeOptions::default();
    native_options.viewport = eframe::egui::ViewportBuilder::default()
        .with_title("ATTPC Merger")
        .with_inner_size(eframe::epaint::vec2(600.0, 300.0));
    native_options.follow_system_theme = false;
    match eframe::run_native(
        "attpc_merger",
        native_options,
        Box::new(|cc| Ok(Box::new(MergerApp::new(cc)))),
    ) {
        Ok(()) => (),
        Err(e) => log::error!("Eframe error: {}", e),
    }
    return;
}
